### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by niakonichan** [raebeb/manga_scraper#4]
Hola, disculpa si describo mi error, no programo y no se nada de programación y no uso github asi que si pongo o falta algo lo siento, no quiero hacerte perder el tiempo 

tengo el siguiente error 

C:\Users\myuser\Desktop\Descargas\manga_scraper-main\manga_scraper-main>python scraper.py "boku no hero academia" -l
Manga found! Downloading...
Finding the last chapter...
Downloading chapter 391... 100%
https://www.mangatigre.net/manga/boku-no-hero-academia/391
JSONDecodeError, trying again...
Traceback (most recent call last):
  File "C:\Users\myuser\Desktop\Descargas\manga_scraper-main\manga_scraper-main\scraper.py", line 21, in <module>
    download_manga(**params)
  File "C:\Users\myuser\Desktop\Descargas\manga_scraper-main\manga_scraper-main\utils.py", line 175, in download_manga
    chapter_dict = json.loads(window_chapter)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

tengo windows y tengo instalado todo de requirements.txt 

gracias n.n

**Comment by niakonichan** [comment]
oh, parece que ahora funciona sin cambiar nada 

Manga found! Downloading...
Downloading chapter 391... 100%
https://www.mangatigre.net/manga/boku-no-hero-academia/391
JSONDecodeError, trying again...
Chapter 391 downloaded! 100%
Done!
Bye! ฅ^•ﻌ•^ฅ
