### ISSUE TITLE
No puedo descargar ciertos capitulos

### ISSUE THREAD

**Issue by ghost** [raebeb/manga_scraper#5]
Hola, buen trabajo !

no puedo descargar capitulos que sean float como 160.5 , me tira error n.n

C:\Users\myuser\Descargas\manga_scraper-main>python scraper.py "name of manga" -i 68 -f last
Manga found! Downloading...
Finding the last chapter...
Traceback (most recent call last):
  File "C:\Users\myuser\Descargas\manga_scraper-main\scraper.py", line 21, in <module>
    download_manga(**params)
  File "C:\Users\myuser\Descargas\manga_scraper-main\utils.py", line 131, in download_manga
    final_chapter = find_last_chapter(manga_title)
  File "C:\Users\myuser\Descargas\manga_scraper-main\utils.py", line 41, in find_last_chapter
    return int(chapter_number)
ValueError: invalid literal for int() with base 10: '68.6'

**Comment by niakonichan** [comment]
@raebeb Hola de nuevo! Funciona en este caso solamente, ejemplo:
Vinland saga: episodios 176 - 176.5 - 177

python scraper.py "vinland saga" -i 176 -f 177   funciona correctamente descargando los tres capitulos

pero si quiero descargar solamente el 176.5 con python scraper.py "vinland saga" -s 176.5 el error es 

usage: scraper.py [-h] [-i INITIAL_CHAPTER] [-f FINAL_CHAPTER] [-l] [-s SINGLE_CHAPTER] manga_title
scraper.py: error: argument -s/--single_chapter: invalid int value: '176.5' 

también si quiero iniciar o finalizar con  176.5 no se puede , por ejemplo python scraper.py "vinland saga" -i 176.5 -f 178 ó  python scraper.py "vinland saga" -i 175 -f 176.5

lo cual hace que para este manga https://www.mangatigre.net/manga/fumetsu-no-anata-e se imposibilite descargarlo por ejemplo 

También probé con python scraper.py "fumetsu no anata e" -l y tampoco funciona.

 Gracias

**Comment by raebeb** [comment]
Hola, ya está fixeado, hice pruebas bajando fumetsu no anata e sin problemas, el error era que se asumía que siempre el último capítulo sería un número entero, espero que ahora si te funcione 🙌

**Comment by ghost** [comment]
Hola @raebeb 🙌 ,  funciona parcialmente, porque sigue asumiendo que el primer capítulo sea un numero entero. Si consideras que merece la pena corregirlo adelante, sino lamento las molestias. Este posible fix evitaría ir hasta el primer capitulo sin "." para poder descargar los necesarios .

python scraper.py "fumetsu no anata e" -i 170.1 -f 173.2
usage: scraper.py [-h] [-i INITIAL_CHAPTER] [-f FINAL_CHAPTER] [-l] [-s SINGLE_CHAPTER] manga_title
scraper.py: error: argument -i/--initial_chapter: invalid int value: '170.1'
